spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    password: root
    url: jdbc:oracle:thin:@//localhost:1521/XE   # Fix URL format
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle21cDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jasper:
    reports:
      path: classpath:/jasper/
